- name: Prevent libapache2-mod-php from being installed
  copy:
    src: libapache2-mod-php.pref
    dest: /etc/apt/preferences.d/

- name: Install apache2
  apt: pkg=apache2 state=present
  register: apache2_installation

- name: Remove default /var/www/html directory after installation
  file: path=/var/www/html state=absent
  when: apache2_installation is changed

- name: Ensure users exist
  user:
    name: "{{ item.user|default(apache_user_prefix + item.name) }}"
  loop: "{{ apache_web_directories }}"

- name: Add groups to apache user
  user:
    name: www-data
    groups: "{{ item.group|default(item.user|default(apache_user_prefix + item.name)) }}"
    append: yes
  loop: "{{ apache_web_directories }}"
  notify: reload apache2

- name: Create web-directories
  file:
    path: "/var/www/{{ item.0.name }}/{{ item.1 }}"
    state: directory
    owner: "{{ item.0.user | default(apache_user_prefix + item.0.name) }}"
    group: "{{ item.0.group | default(item.0.user|default(apache_user_prefix + item.0.name)) }}"
    mode: "{{ item.0.mode | default('0710') }}"
  with_nested:
    - "{{ apache_web_directories }}"
    - ['', 'htdocs','logs']

- name: Copy site files
  template:
    src: "{{ item }}"
    dest: /etc/apache2/sites-available/
  with_fileglob: "{{ apache_sites_path }}/*"
  notify: reload apache2

- name: Copy includes
  copy: src=includes/ dest=/etc/apache2/includes/
  notify: reload apache2

- name: Copy custom includes
  copy: src={{ apache2_include_path }} dest=/etc/apache2/includes/
  when: apache2_include_path is defined
  notify: reload apache2

- name: Copy macros
  copy: src=macros/ dest=/etc/apache2/macros/
  notify: reload apache2

- name: Copy custom macros
  copy: src={{ apache2_macros_path }} dest=/etc/apache2/macros/
  when: apache2_macros_path is defined
  notify: reload apache2

- name: Copy config files
  copy: src=conf/ dest=/etc/apache2/conf-available/
  notify: reload apache2

- name: Copy custom mods files
  copy: src={{ apache2_mods_path }} dest=/etc/apache2/mods-available/
  when: apache2_mods_path is defined
  notify: reload apache2

- name: Enable apache modules
  apache2_module: name={{ item }} state=present
  with_items: "{{ apache_enable_modules }}"
  notify: restart apache2

- name: Activate configuration
  command:
    a2enconf {{ item }}.conf
    creates=/etc/apache2/conf-enabled/{{ item }}.conf
  with_items:
    - protect-git
    - enable-http2
    - include-macros
  notify: reload apache2

- name: Install vhost logrotation
  copy: src=logrotate dest=/etc/logrotate.d/apache-vhost-logs

- name: Create /var/www/default for catch-all host
  file: path=/var/www/default state=directory

- name: Install catch-all http vhost
  copy: src=000-default.conf dest=/etc/apache2/sites-available/000-default.conf
  notify: reload apache2

- name: Enable catch-all http vhost
  file:
    src: "/etc/apache2/sites-available/000-default.conf"
    dest: "/etc/apache2/sites-enabled/000-default.conf"
    state: link
  notify: reload apache2

- name: Ensure apache2 is started
  service:
    name: apache2
    state: started
    enabled: yes
